/**
 * HookSniff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { type PolledMessage, PolledMessageSerializer } from "./polledMessage";
import { type MessagePollerCursor, MessagePollerCursorSerializer } from "./messagePollerCursor";

export interface MessagePollerPollResponse {
  messages: PolledMessage[];
  cursor: MessagePollerCursor;
  done: boolean;
}

export const MessagePollerPollResponseSerializer = {
  _fromJsonObject(json: any): MessagePollerPollResponse {
    return {
      messages: json['messages'].map((item: any) => PolledMessageSerializer._fromJsonObject(item)),
      cursor: MessagePollerCursorSerializer._fromJsonObject(json['cursor']),
      done: json['done'],
    };
  },

  _toJsonObject(instance: MessagePollerPollResponse): any {
    return {
      'messages': instance.messages.map(item => PolledMessageSerializer._toJsonObject(item)),
      'cursor': MessagePollerCursorSerializer._toJsonObject(instance.cursor),
      'done': instance.done,
    };
  },
};
