/**
 * HookSniff API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PolledMessage {
  id: string;
  endpointId: string;
  eventType?: string | null;
  status: string;
  attemptCount: number;
  responseStatus?: number | null;
  createdAt: string;
  payload?: any | null;
}

export const PolledMessageSerializer = {
  _fromJsonObject(json: any): PolledMessage {
    return {
      id: json['id'],
      endpointId: json['endpoint_id'],
      eventType: json['event_type'] ?? null,
      status: json['status'],
      attemptCount: json['attempt_count'],
      responseStatus: json['response_status'] ?? null,
      createdAt: json['created_at'],
      payload: json['payload'] ?? null,
    };
  },

  _toJsonObject(instance: PolledMessage): any {
    return {
      'id': instance.id,
      'endpoint_id': instance.endpointId,
      'event_type': instance.eventType,
      'status': instance.status,
      'attempt_count': instance.attemptCount,
      'response_status': instance.responseStatus,
      'created_at': instance.createdAt,
      'payload': instance.payload,
    };
  },
};
